d

diff --git a/.github/workflows/AWS-Deploy.yml b/.github/workflows/AWS-Deploy.yml
--- a/.github/workflows/AWS-Deploy.yml
+++ b/.github/workflows/AWS-Deploy.yml
@@ -42,9 +42,14 @@ jobs:
                 #!/bin/bash
                 yum update -y
                 amazon-linux-extras install -y docker
-                service docker start
+                systemctl start docker
                 systemctl enable docker
                 usermod -a -G docker ec2-user
+                if ! command -v docker &> /dev/null
+                then
+                    echo "Docker could not be installed"
+                    exit 1
+                fi
                 EOF
                 )
                 INSTANCE_ID=$(aws ec2 run-instances \
@@ -59,6 +64,7 @@ jobs:
                   --output text)
                 echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
                 aws ec2 wait instance-running --instance-ids $INSTANCE_ID
+        
         
       - name: Get EC2 instance IP
         run: |
